server:
  port: 8084

spring.datasource.url: jdbc:h2:file:./camunda-h2-database

camunda.bpm:
  admin-user:
    id: demo
    password: demo
  filter.create: All Tasks

account.uri: http://localhost:8081/accounts

spring:
  cloud:
    function:
      definition: issueCard
    stream:
      kafka:
        bindings:

          issueCard-out-0:
            producer:
              configuration:
                value.serializer: com.example.eventbank.customerregistration.dto.converters.MessageSerializer

          issueCard-in-0:
            consumer:
              configuration:
                value.deserializer: com.example.eventbank.customerregistration.dto.converters.MessageDeSerializer

          notification-out-0:
            producer:
              configuration:
                value.serializer: com.example.eventbank.customerregistration.dto.converters.MessageSerializer

        binder:
          brokers: localhost:29092

      bindings:
        issueCard-out-0:
          destination: issue-card-events
          producer:
            useNativeEncoding: true

        issueCard-in-0:
          destination: issue-card-events
          consumer:
            use-native-decoding: true

        notification-out-0:
          destination: notification-events
          producer:
            useNativeEncoding: true
      default-binder: kafka

  jackson:
    serialization:
      write-dates-as-timestamps: false