server:
  port: 8083

spring:
  cloud:
    function:
      definition: consumer
    stream:
      kafka:
        bindings:

          consumer-in-0:
            consumer:
              configuration:
                value.deserializer: com.example.eventbank.notifications.dto.converters.MessageDeSerializer

        binder:
          brokers: localhost:29092

      bindings:

        consumer-in-0:
          destination: notification
          consumer:
            use-native-decoding: true

  jackson:
    serialization:
      write-dates-as-timestamps: false


  spring.mail.host: smtp.gmail.com
  spring.mail.port: 587
  spring.mail.username: <login user to smtp server>
  spring.mail.password: wxncehuqnezuwaoi
  spring.mail.properties.mail.smtp.auth: true
  spring.mail.properties.mail.smtp.starttls.enable: true
