server:
  port: 8081

spring:
  cloud:
    function:
      definition: producer;consumer;globalConsumer
    stream:
      kafka:
        bindings:

          payment-out-0:
            producer:
              configuration:
                value.serializer: com.example.eventbank.accounts.dto.converters.MessageSerializer

          consumer-in-0:
            consumer:
              configuration:
                value.deserializer: com.example.eventbank.accounts.dto.converters.MessageDeSerializer

        binder:
          brokers: localhost:29092

      bindings:

        payment-out-0:
          destination: payment-events
          producer:
            useNativeEncoding: true

        consumer-in-0:
          destination: payment-events
          consumer:
            use-native-decoding: true

  jackson:
    serialization:
      write-dates-as-timestamps: false
