server:
  port: 8081

spring:
  cloud:
    function:
      definition: producer;paymentRequest;globalConsumer
    stream:
      kafka:
        bindings:

          payment-out-0:
            producer:
              configuration:
                value.serializer: com.example.eventbank.accounts.dto.converters.MessageSerializer

          paymentRequest-in-0:
            consumer:
              configuration:
                value.deserializer: com.example.eventbank.accounts.dto.converters.MessageDeSerializer


        binder:
          brokers: localhost:29092
          autoAddPartitions: true
          minPartitionCount: 1

      bindings:

        payment-out-0:
          destination: payment-reply-events
          producer:
            partition-count: 1
            useNativeEncoding: true

        paymentRequest-in-0:
          destination: payment-extended-events
          consumer:
            use-native-decoding: true

  jackson:
    serialization:
      write-dates-as-timestamps: false
