server:
  port : 8081

spring:
  cloud:
    function:
      definition: producer;consumer;globalConsumer
    stream:
      kafka:
        bindings:

          global-out-0:
            producer:
              configuration:
                value.serializer: com.example.eventbank.accounts.dto.converters.MessageSerializer
          global-in-0:
            consumer:
              configuration:
                value.deserializer: com.example.eventbank.accounts.dto.converters.MessageDeSerializer

        binder:
          brokers: localhost:29092

      bindings:
        global-out-0:
          destination: global-events
          producer:
            useNativeEncoding: true
        global-in-0:
          destination : global-events
          globalConsumer:
            use-native-decoding: true

  jackson:
    serialization:
      write-dates-as-timestamps: false