server:
  port : 8082

spring:
  cloud:
    function:
      definition: producer;consumer;globalConsumer
    stream:
      kafka:
        bindings:

          payment-out-0:
            producer:
              configuration:
                value.serializer: com.example.eventbank.cards.dto.converters.MessageSerializer
          payment-in-0:
            consumer:
              configuration:
                value.deserializer: com.example.eventbank.cards.dto.converters.MessageDeSerializer

        binder:
          brokers: localhost:29092

      bindings:
        payment-out-0:
          destination: payment-events
          producer:
            useNativeEncoding: true
        payment-in-0:
          destination : payment-events
          globalConsumer:
            use-native-decoding: true

  jackson:
    serialization:
      write-dates-as-timestamps: false
