server:
  port: 8084

spring.datasource.url: jdbc:h2:file:./camunda-h2-database

camunda.bpm:
  admin-user:
    id: demo
    password: demo
  filter.create: All Tasks

kafka:
  bootstrap-address: localhost:9092
  group-id: someGroupId
  trusted-packages: com.example.eventbank.customerregistration.dto

account.uri: http://localhost:8081/accounts

spring:
  cloud:
    function:
      definition: consumer
    stream:
      kafka:
        bindings:

          payment-out-0:
            producer:
              configuration:
                value.serializer: com.example.eventbank.customerregistration.dto.converters.MessageSerializer

          consumer-in-0:
            consumer:
              configuration:
                value.deserializer: com.example.eventbank.customerregistration.dto.converters.MessageDeSerializer

          notification-out-0:
            producer:
              configuration:
                value.serializer: com.example.eventbank.customerregistration.dto.converters.MessageSerializer

        binder:
          brokers: localhost:29092

      bindings:
        payment-out-0:
          destination: payment-events
          producer:
            useNativeEncoding: true

        consumer-in-0:
          destination: payment-events
          consumer:
            use-native-decoding: true

        notification-out-0:
          destination: notification
          producer:
            useNativeEncoding: true
      default-binder: kafka

  jackson:
    serialization:
      write-dates-as-timestamps: false