server:
  port: 8083

spring:
  cloud:
    function:
      definition: consumer
    stream:
      kafka:
        bindings:

          consumer-in-0:
            consumer:
              configuration:
                value.deserializer: com.example.eventbank.notifications.dto.converters.MessageDeSerializer

        binder:
          brokers: localhost:29092
          autoAddPartitions: true
          minPartitionCount: 4

      bindings:

        consumer-in-0:
          destination: notification-events
          consumer:
            use-native-decoding: true

  jackson:
    serialization:
      write-dates-as-timestamps: false
